In [1]:
import pandas as pd
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df = pd.read_csv(url, header=None)

In [2]:
print(df)

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa


In [3]:
print(df.loc[0])

0            5.1
1            3.5
2            1.4
3            0.2
4    Iris-setosa
Name: 0, dtype: object


In [4]:
data = df.values
X = data[:,:-1]
y = data[:,-1]

In [5]:
#X przestrzeń cech — zbiór wszystkich wektorów cech obiektów znajdujących się w zbiorze
print(X.shape)

(150, 4)


In [6]:
#y zbiór etykiet — zawierający etykiety dla obiektów znajdujących się w zbiorze 
print(y.shape)

(150,)


In [7]:
#1.2 Podział zbioru danych na uczący i testowy

In [10]:
from sklearn import model_selection
splits = model_selection.train_test_split(X, y, test_size=.333, random_state=0)
X_train, X_test, y_train, y_test = splits
print (X_train.shape, X_test.shape, y_train.shape, y_test.shape)

k = 10
cv = model_selection.StratifiedKFold(n_splits=k)

fold = 0
for train, test in cv.split(X_train, y_train):
    print ("Fold %i (%i w TS, %i w VS)" % (fold, len(train), len(test)))
    print (train)
    fold += 1

(100, 4) (50, 4) (100,) (50,)
Fold 0 (88 w TS, 12 w VS)
[ 7  9 10 12 13 14 15 16 17 20 21 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Fold 1 (89 w TS, 11 w VS)
[ 0  1  2  3  4  5  6  8 11 15 16 18 19 20 21 22 24 26 27 29 30 31 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82
 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Fold 2 (89 w TS, 11 w VS)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 17 18 19 22 23 24 25 27 28
 29 31 32 34 35 36 39 40 42 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82
 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Fold 3 (89 w TS, 11 w VS)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 1

In [11]:
#algorytm k najbliższych sąsiadów
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier() #konkretny klasyfikator
clf.fit(X_train, y_train) #Wytrenuj klasyfikator korzystając z zbioru danych
score = clf.score(X_test, y_test) #Określ jakość klasyfikatora
print(score)

0.98


In [7]:
support_vector = clf.predict_proba(X_test)
print(support_vector)

[[0.  0.  1. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.2 0.8]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.6 0.4]
 [1.  0.  0. ]
 [0.  0.8 0.2]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.2 0.8]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  0.2 0.8]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.4 0.6]
 [0.  0.  1. ]]


In [8]:
import numpy as np

prediction = np.argmax(support_vector,axis = 1)
print(prediction)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0 1 2 2 2 2]


In [9]:
#Posłuż się atrybutem classes_ "przetłumaczenia" indeksów klas predykcji na odpowiadające im łańcuchy znakowe
prediction = clf.classes_[prediction]
print(prediction)

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica']


In [10]:
from sklearn import metrics

confusion_matrix = metrics.confusion_matrix(y_test, prediction)
print(confusion_matrix)

[[16  0  0]
 [ 0 18  1]
 [ 0  0 15]]


In [11]:
accuracy = metrics.accuracy_score(y_test, prediction)
print (accuracy)

0.98


In [12]:
k = 10 # 10 podziałów. 
cv = model_selection.StratifiedKFold(n_splits=k) 

accuracies = [] #kolejne wyliczone dokładności
for train, test in cv.split(X, y):
    #Odpowiednie podzbiory tablic
    X_train, y_train = X[train], y[train]
    X_test, y_test = X[test], y[test]

    clf.fit(X_train, y_train) #ucz klasyfikator
    probas = clf.predict_proba(X_test) #wyliczamy wektory wsparć
    # wyliczamy i tłumaczymy predykcję i wyliczamy dokładność
    prediction = np.argmax(probas,axis = 1)
    prediction = clf.classes_[prediction]
    accuracy = metrics.accuracy_score(y_test, prediction)
    accuracies.append(accuracy)

print (accuracies)

[1.0, 0.9333333333333333, 1.0, 1.0, 0.8666666666666667, 0.9333333333333333, 0.9333333333333333, 1.0, 1.0, 1.0]


In [13]:
#Uśredniona dokładność i odchylenie standardowe.
mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)
print ("Średnia dokładność %.3f (+- %.2f)" % (mean_accuracy, std_accuracy))

Średnia dokładność 0.967 (+- 0.04)


In [14]:
from sklearn import neighbors
clfs = [
    neighbors.KNeighborsClassifier(n_neighbors = 1),
    neighbors.KNeighborsClassifier(n_neighbors = 5)
]

#wczytamy zbiór danych, dzieląc go na przestrzeń cech i zbiór etykiet
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df = pd.read_csv(url, header=None)
data = df.values
X = data[:,:-1]
y = data[:,-1]

#Podział zbioru z użyciem k-foldowej walidacji krzyżowej
k = 10
cv = model_selection.StratifiedKFold(n_splits=k)

results = []
for train, test in cv.split(X,y):
    X_train, y_train = X[train], y[train]
    X_test, y_test = X[test], y[test]
    result = []
    for clf in clfs:
        clf.fit(X_train, y_train)
        probas = clf.predict_proba(X_test)
        prediction = np.argmax(probas,axis = 1)
        prediction = clf.classes_[prediction]
        accuracy = metrics.accuracy_score(y_test, prediction),
        result.append(accuracy[0])
    results.append(result)
results = np.array(results)

print(results)

[[1.         1.        ]
 [0.93333333 0.93333333]
 [1.         1.        ]
 [0.93333333 1.        ]
 [0.86666667 0.86666667]
 [1.         0.93333333]
 [0.86666667 0.93333333]
 [1.         1.        ]
 [1.         1.        ]
 [1.         1.        ]]


In [15]:
#testy statystyczne
from scipy import stats
test_t = stats.ttest_ind(results[:,0],results[:,1])
test_w = stats.wilcoxon(results[:,0],results[:,1])
print (np.mean(results,axis=0))

[0.96       0.96666667]


C:\Users\Ragnus\Anaconda3\lib\site-packages\scipy\stats\morestats.py:2778: UserWarning: Warning: sample size too small for normal approximation.
  warnings.warn("Warning: sample size too small for normal approximation.")


In [16]:
print (test_t)
print (test_w)

Ttest_indResult(statistic=-0.2873478855663521, pvalue=0.7771278487505224)
WilcoxonResult(statistic=2.0, pvalue=0.5637028616507731)
